CREATE TABLE IF NOT EXISTS public."__IdentityMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___IdentityMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'identity') THEN
            CREATE SCHEMA identity;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE TABLE identity."Roles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE TABLE identity."Users" (
        "Id" text NOT NULL,
        "FullName" text NOT NULL,
        "CompanyId" uuid,
        "Role" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE TABLE identity."RoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES identity."Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE TABLE identity."UserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE TABLE identity."UserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE TABLE identity."UserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES identity."Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE TABLE identity."UserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE INDEX "IX_RoleClaims_RoleId" ON identity."RoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON identity."Roles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE INDEX "IX_UserClaims_UserId" ON identity."UserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE INDEX "IX_UserLogins_UserId" ON identity."UserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE INDEX "IX_UserRoles_RoleId" ON identity."UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE INDEX "EmailIndex" ON identity."Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON identity."Users" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216154104_InitialIdentity') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251216154104_InitialIdentity', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216224325_AddRefreshToken') THEN
    CREATE TABLE identity."RefreshTokens" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "CustomerId" uuid,
        "Token" character varying(500) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "RevokedAt" timestamp with time zone,
        "ReplacedByToken" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216224325_AddRefreshToken') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON identity."RefreshTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216224325_AddRefreshToken') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON identity."RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251216224325_AddRefreshToken') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251216224325_AddRefreshToken', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251217041740_PendingChanges') THEN
    ALTER TABLE identity."RefreshTokens" ADD "TenantId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251217041740_PendingChanges') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251217041740_PendingChanges', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220053610_AddDriverGpsLocation') THEN
    ALTER TABLE identity."Users" ADD "CurrentLatitude" numeric(18,8);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220053610_AddDriverGpsLocation') THEN
    ALTER TABLE identity."Users" ADD "CurrentLongitude" numeric(18,8);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220053610_AddDriverGpsLocation') THEN
    ALTER TABLE identity."Users" ADD "LocationUpdatedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220053610_AddDriverGpsLocation') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251220053610_AddDriverGpsLocation', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220090617_AddOnboardingAndDriverType') THEN
    ALTER TABLE identity."Users" ADD "BusinessType" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220090617_AddOnboardingAndDriverType') THEN
    ALTER TABLE identity."Users" ADD "IsOnboarded" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220090617_AddOnboardingAndDriverType') THEN
    ALTER TABLE identity."Users" ADD "IsSoloDriver" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220090617_AddOnboardingAndDriverType') THEN
    CREATE INDEX "IX_Users_BusinessType" ON identity."Users" ("BusinessType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220090617_AddOnboardingAndDriverType') THEN
    CREATE INDEX "IX_Users_IsOnboarded" ON identity."Users" ("IsOnboarded");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220090617_AddOnboardingAndDriverType') THEN
    CREATE INDEX "IX_Users_IsSoloDriver" ON identity."Users" ("IsSoloDriver");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251220090617_AddOnboardingAndDriverType') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251220090617_AddOnboardingAndDriverType', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251224065541_AddSoftDeleteAndAuditLog') THEN
    ALTER TABLE identity."RefreshTokens" ADD "DeletedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251224065541_AddSoftDeleteAndAuditLog') THEN
    ALTER TABLE identity."RefreshTokens" ADD "DeletedBy" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251224065541_AddSoftDeleteAndAuditLog') THEN
    ALTER TABLE identity."RefreshTokens" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251224065541_AddSoftDeleteAndAuditLog') THEN
    CREATE TABLE identity."AuditLogs" (
        "Id" uuid NOT NULL,
        "Action" character varying(100) NOT NULL,
        "Category" character varying(50) NOT NULL,
        "UserId" character varying(450),
        "UserName" character varying(256),
        "UserEmail" character varying(256),
        "UserRole" character varying(50),
        "EntityId" character varying(450),
        "EntityType" character varying(100),
        "Details" text,
        "IpAddress" character varying(45),
        "IsSuccess" boolean NOT NULL,
        "ErrorMessage" character varying(1000),
        "Timestamp" timestamp with time zone NOT NULL,
        "IsArchived" boolean NOT NULL,
        "ArchivedAt" timestamp with time zone,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251224065541_AddSoftDeleteAndAuditLog') THEN
    CREATE INDEX "IX_AuditLogs_Category" ON identity."AuditLogs" ("Category");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251224065541_AddSoftDeleteAndAuditLog') THEN
    CREATE INDEX "IX_AuditLogs_IsArchived" ON identity."AuditLogs" ("IsArchived");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251224065541_AddSoftDeleteAndAuditLog') THEN
    CREATE INDEX "IX_AuditLogs_Timestamp" ON identity."AuditLogs" ("Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251224065541_AddSoftDeleteAndAuditLog') THEN
    CREATE INDEX "IX_AuditLogs_UserId" ON identity."AuditLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251224065541_AddSoftDeleteAndAuditLog') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251224065541_AddSoftDeleteAndAuditLog', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251226125013_AddDriverOnlineStatus') THEN
    ALTER TABLE identity."Users" ADD "IsOnline" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251226125013_AddDriverOnlineStatus') THEN
    CREATE INDEX "IX_Users_IsOnline" ON identity."Users" ("IsOnline");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20251226125013_AddDriverOnlineStatus') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251226125013_AddDriverOnlineStatus', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260105040742_AddSecurityQuestions') THEN
    ALTER TABLE identity."Users" ADD "SecurityAnswerHash1" character varying(256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260105040742_AddSecurityQuestions') THEN
    ALTER TABLE identity."Users" ADD "SecurityAnswerHash2" character varying(256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260105040742_AddSecurityQuestions') THEN
    ALTER TABLE identity."Users" ADD "SecurityAnswerHash3" character varying(256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260105040742_AddSecurityQuestions') THEN
    ALTER TABLE identity."Users" ADD "SecurityQuestionId1" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260105040742_AddSecurityQuestions') THEN
    ALTER TABLE identity."Users" ADD "SecurityQuestionId2" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260105040742_AddSecurityQuestions') THEN
    ALTER TABLE identity."Users" ADD "SecurityQuestionId3" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260105040742_AddSecurityQuestions') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260105040742_AddSecurityQuestions', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260114055402_AddProfilePictureUrl') THEN
    ALTER TABLE identity."Users" ADD "ProfilePictureUrl" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260114055402_AddProfilePictureUrl') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260114055402_AddProfilePictureUrl', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260211094050_AddLivenessVerifiedAt') THEN
    ALTER TABLE identity."Users" ADD "LivenessVerifiedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260211094050_AddLivenessVerifiedAt') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260211094050_AddLivenessVerifiedAt', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216000000_AddDriverVehicleInfo') THEN
    ALTER TABLE identity."Users" ADD "VehiclePlate" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216000000_AddDriverVehicleInfo') THEN
    ALTER TABLE identity."Users" ADD "VehicleModel" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216000000_AddDriverVehicleInfo') THEN
    ALTER TABLE identity."Users" ADD "VehicleColor" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216000000_AddDriverVehicleInfo') THEN
    ALTER TABLE identity."Users" ADD "VehicleType" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216000000_AddDriverVehicleInfo') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260216000000_AddDriverVehicleInfo', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216063146_AddDriverVehicleRelations') THEN
    CREATE TABLE identity."Vehicles" (
        "Id" uuid NOT NULL,
        "PlateNumber" character varying(20) NOT NULL,
        "Model" character varying(100),
        "Color" character varying(50),
        "Type" character varying(50),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216063146_AddDriverVehicleRelations') THEN
    CREATE TABLE identity."DriverVehicleAssignments" (
        "Id" uuid NOT NULL,
        "DriverId" text NOT NULL,
        "VehicleId" uuid NOT NULL,
        "IsPrimary" boolean NOT NULL,
        "AssignedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DriverVehicleAssignments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DriverVehicleAssignments_Users_DriverId" FOREIGN KEY ("DriverId") REFERENCES identity."Users" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DriverVehicleAssignments_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES identity."Vehicles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216063146_AddDriverVehicleRelations') THEN
    CREATE INDEX "IX_DriverVehicleAssignments_DriverId" ON identity."DriverVehicleAssignments" ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216063146_AddDriverVehicleRelations') THEN
    CREATE INDEX "IX_DriverVehicleAssignments_DriverId_IsPrimary" ON identity."DriverVehicleAssignments" ("DriverId", "IsPrimary");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216063146_AddDriverVehicleRelations') THEN
    CREATE UNIQUE INDEX "IX_DriverVehicleAssignments_DriverId_VehicleId" ON identity."DriverVehicleAssignments" ("DriverId", "VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216063146_AddDriverVehicleRelations') THEN
    CREATE INDEX "IX_DriverVehicleAssignments_VehicleId" ON identity."DriverVehicleAssignments" ("VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216063146_AddDriverVehicleRelations') THEN
    CREATE UNIQUE INDEX "IX_Vehicles_PlateNumber" ON identity."Vehicles" ("PlateNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216063146_AddDriverVehicleRelations') THEN
    INSERT INTO identity."Vehicles" ("Id", "PlateNumber", "Model", "Color", "Type", "CreatedAt")
    SELECT
        (
            substr(md5('veh:' || upper(trim(u."VehiclePlate"))), 1, 8) || '-' ||
            substr(md5('veh:' || upper(trim(u."VehiclePlate"))), 9, 4) || '-' ||
            substr(md5('veh:' || upper(trim(u."VehiclePlate"))), 13, 4) || '-' ||
            substr(md5('veh:' || upper(trim(u."VehiclePlate"))), 17, 4) || '-' ||
            substr(md5('veh:' || upper(trim(u."VehiclePlate"))), 21, 12)
        )::uuid AS "Id",
        upper(trim(u."VehiclePlate")) AS "PlateNumber",
        NULLIF(trim(u."VehicleModel"), '') AS "Model",
        NULLIF(trim(u."VehicleColor"), '') AS "Color",
        NULLIF(trim(u."VehicleType"), '') AS "Type",
        NOW() AS "CreatedAt"
    FROM identity."Users" u
    WHERE u."VehiclePlate" IS NOT NULL
      AND btrim(u."VehiclePlate") <> ''
    ON CONFLICT ("PlateNumber") DO NOTHING;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216063146_AddDriverVehicleRelations') THEN
    INSERT INTO identity."DriverVehicleAssignments" ("Id", "DriverId", "VehicleId", "IsPrimary", "AssignedAt")
    SELECT
        (
            substr(md5('drvveh:' || u."Id" || ':' || v."Id"::text), 1, 8) || '-' ||
            substr(md5('drvveh:' || u."Id" || ':' || v."Id"::text), 9, 4) || '-' ||
            substr(md5('drvveh:' || u."Id" || ':' || v."Id"::text), 13, 4) || '-' ||
            substr(md5('drvveh:' || u."Id" || ':' || v."Id"::text), 17, 4) || '-' ||
            substr(md5('drvveh:' || u."Id" || ':' || v."Id"::text), 21, 12)
        )::uuid AS "Id",
        u."Id" AS "DriverId",
        v."Id" AS "VehicleId",
        TRUE AS "IsPrimary",
        NOW() AS "AssignedAt"
    FROM identity."Users" u
    INNER JOIN identity."Vehicles" v
        ON v."PlateNumber" = upper(trim(u."VehiclePlate"))
    WHERE u."VehiclePlate" IS NOT NULL
      AND btrim(u."VehiclePlate") <> ''
    ON CONFLICT ("DriverId", "VehicleId")
    DO UPDATE SET "IsPrimary" = TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM public."__IdentityMigrationsHistory" WHERE "MigrationId" = '20260216063146_AddDriverVehicleRelations') THEN
    INSERT INTO public."__IdentityMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260216063146_AddDriverVehicleRelations', '10.0.1');
    END IF;
END $EF$;
COMMIT;

